# ============================
# Dev environment overrides
# ============================

namespace: infra-portal-dev

backend:
  replicaCount: 1
  profile: dev
  securityEnabled: "false"
  corsAllowedOrigins: "*"

  image:
    tag: dev-latest

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  autoscaling:
    enabled: false

ui:
  replicaCount: 1

  image:
    tag: dev-latest

  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

ingress:
  host: infra-portal-dev.cubic.com
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: ""
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
