import logging
from fastapi import APIRouter, HTTPException, status
from app.schemas import (
    ProvisionEnvironmentRequest,
    ProvisionEnvironmentResponse,
    HealthResponse,
    ClusterRegistrationRequest,
    ClusterRegistrationResponse,
)
from app.template_engine import (
    render_tfvars,
    build_changes_summary,
    render_cluster_register,
    render_cluster_values,
    build_cluster_changes_summary,
)
from app.github_service import GitHubService
from app.config import get_settings
from app.workflow_updater import (
    VALIDATE_PLAN_PATH,
    PLAN_DEPLOY_PATH,
    patch_validate_plan_workflow,
    patch_plan_deploy_workflow,
)
from app.appset_updater import (
    APPLICATIONSET_PATH,
    patch_projects_list,
    AppSetPatchError,
)
from app.envmatch_updater import (
    ADOT_COLLECTOR_PATH,
    patch_environment_match_values,
    EnvMatchPatchError,
)

logger = logging.getLogger(__name__)
router = APIRouter()


@router.get("/health", response_model=HealthResponse, tags=["system"])
async def health_check():
    return HealthResponse()


@router.post(
    "/provision/environment",
    response_model=ProvisionEnvironmentResponse,
    tags=["provisioning"],
)
async def provision_environment(request: ProvisionEnvironmentRequest):
    """
    Provision a new environment.

    This endpoint:
    1. Validates the input.
    2. Checks the environment doesn't already exist.
    3. Generates the terraform.tfvars from a template.
    4. Creates a new branch in GitHub.
    5. Commits the generated file.
    6. Raises a pull request with full details.
    """

    branch_name = request.derive_branch_name()
    file_path = f"environments/{request.environment_name}/terraform.tfvars"

    try:
        gh = GitHubService()
    except Exception:
        logger.exception("Failed to connect to GitHub")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Unable to connect to GitHub. Check GITHUB_TOKEN.",
        )

    # --- Guard: environment already exists ---
    if gh.environment_exists(request.environment_name):
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"Environment '{request.environment_name}' already exists in the repository.",
        )

    # --- Guard: branch already exists ---
    if gh.branch_exists(branch_name):
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"Branch '{branch_name}' already exists. Use a different Jira ticket or delete the existing branch.",
        )

    # --- Render template ---
    try:
        tfvars_content = render_tfvars(request)
    except Exception:
        logger.exception("Template rendering failed")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to generate Terraform configuration.",
        )

    changes_summary = build_changes_summary(request)

    # --- Create branch ---
    try:
        gh.create_branch(branch_name)
    except ValueError as ve:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=str(ve),
        )
    except Exception:
        logger.exception("Failed to create branch %s", branch_name)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Failed to create branch '{branch_name}' in GitHub.",
        )

    # --- Commit file ---
    commit_message = (
        f"feat: add tfvars for {request.environment_name}\n\n"
        f"Auto-generated by Infra Portal.\n"
        f"Resources: bastion, VPC (primary + secondary), VPC flow logs IAM, app config mgmt"
    )

    try:
        gh.commit_file(branch_name, file_path, tfvars_content, commit_message)
    except Exception:
        logger.exception("Failed to commit file")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Failed to commit Terraform file to GitHub.",
        )

    # --- Update CI/CD workflows to include the new environment ---
    try:
        # Patch terraform_validate_plan.yml
        vp_content = gh.get_file_content(VALIDATE_PLAN_PATH, ref=branch_name)
        vp_patched = patch_validate_plan_workflow(
            vp_content, request.environment_name, request.aws_account_id
        )
        if vp_patched != vp_content:
            gh.update_file(
                branch_name,
                VALIDATE_PLAN_PATH,
                vp_patched,
                f"ci: add {request.environment_name} to validate/plan workflow",
            )

        # Patch terraform_plan_deploy.yml
        pd_content = gh.get_file_content(PLAN_DEPLOY_PATH, ref=branch_name)
        pd_patched = patch_plan_deploy_workflow(
            pd_content, request.environment_name, request.aws_account_id
        )
        if pd_patched != pd_content:
            gh.update_file(
                branch_name,
                PLAN_DEPLOY_PATH,
                pd_patched,
                f"ci: add {request.environment_name} to plan/deploy workflow",
            )
    except Exception:
        logger.exception("Failed to update workflow files")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="tfvars committed, but failed to update CI/CD workflow files.",
        )

    # --- Create PR ---
    try:
        pr_url, pr_number = gh.create_pull_request(
            branch_name, request, changes_summary, file_path
        )
    except Exception:
        logger.exception("Failed to create pull request")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Branch and commit created, but failed to create the pull request.",
        )

    return ProvisionEnvironmentResponse(
        success=True,
        message=f"PR #{pr_number} created successfully for environment '{request.environment_name}'.",
        branch_name=branch_name,
        pr_url=pr_url,
        pr_number=pr_number,
        file_path=file_path,
        changes_summary=changes_summary,
    )


@router.post(
    "/provision/environment/preview",
    tags=["provisioning"],
)
async def preview_environment(request: ProvisionEnvironmentRequest):
    """Preview the generated terraform.tfvars without creating a PR."""
    tfvars_content = render_tfvars(request)
    changes_summary = build_changes_summary(request)
    return {
        "file_path": f"environments/{request.environment_name}/terraform.tfvars",
        "branch_name": request.derive_branch_name(),
        "content": tfvars_content,
        "changes_summary": changes_summary,
    }


# ───────────────────────────────────────────────────────────────────
#  Cluster Registration (ArgoCD)
# ───────────────────────────────────────────────────────────────────

@router.post(
    "/cluster-registration/preview",
    tags=["cluster-registration"],
)
async def preview_cluster_registration(request: ClusterRegistrationRequest):
    """Preview the rendered cluster registration YAML files."""
    return {
        "register_file_path": request.register_file_path(),
        "values_file_path": request.values_file_path(),
        "branch_name": request.pr_branch_name,
        "register_content": render_cluster_register(request),
        "values_content": render_cluster_values(request),
        "changes_summary": build_cluster_changes_summary(request),
    }


@router.post(
    "/cluster-registration",
    response_model=ClusterRegistrationResponse,
    tags=["cluster-registration"],
)
async def register_cluster(request: ClusterRegistrationRequest):
    """Register a new EKS cluster with ArgoCD by creating PR in the app-of-apps repo."""

    settings = get_settings()
    branch_name = request.pr_branch_name
    register_path = request.register_file_path()
    values_path = request.values_file_path()

    try:
        gh = GitHubService(
            repo_full_name=settings.argocd_github_repo_full,
            base_branch=settings.argocd_github_base_branch,
        )
    except Exception:
        logger.exception("Failed to connect to GitHub (argocd repo)")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Unable to connect to GitHub. Check GITHUB_TOKEN.",
        )

    # Guard: file already exists on base branch
    try:
        existing = gh.get_file_content(register_path)
        if existing:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"Cluster registration file already exists: {register_path}",
            )
    except HTTPException:
        raise
    except Exception:
        # 404 expected — file should not exist
        pass

    # Guard: branch already exists
    if gh.branch_exists(branch_name):
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"Branch '{branch_name}' already exists. Choose a different name.",
        )

    # Render templates
    try:
        register_content = render_cluster_register(request)
        values_content = render_cluster_values(request)
    except Exception:
        logger.exception("Template rendering failed")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to render cluster registration templates.",
        )

    # Create branch
    try:
        gh.create_branch(branch_name)
    except ValueError as ve:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=str(ve))
    except Exception:
        logger.exception("Failed to create branch %s", branch_name)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Failed to create branch '{branch_name}'.",
        )

    # Commit both files
    try:
        gh.commit_file(
            branch_name,
            register_path,
            register_content,
            f"feat: register {request.cluster_name()} cluster with ArgoCD",
        )
        gh.commit_file(
            branch_name,
            values_path,
            values_content,
            f"feat: add cluster-values for {request.cluster_name()}",
        )
    except Exception:
        logger.exception("Failed to commit cluster registration files")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Failed to commit registration files to GitHub.",
        )

    # Patch the ApplicationSet registry so ArgoCD actually picks up the new
    # cluster. Read from the base branch, append the project name, and commit
    # on the same feature branch. Idempotent: skip commit if already present.
    appset_patched = False
    try:
        appset_content = gh.get_file_content(APPLICATIONSET_PATH)
        updated_appset, changed = patch_projects_list(
            appset_content, request.project_name()
        )
        if changed:
            gh.update_file(
                branch_name,
                APPLICATIONSET_PATH,
                updated_appset,
                f"feat: register {request.project_name()} in ApplicationSet projects",
            )
            appset_patched = True
            logger.info(
                "Patched ApplicationSet projects list with '%s'",
                request.project_name(),
            )
        else:
            logger.info(
                "ApplicationSet already lists project '%s' \u2014 skipping",
                request.project_name(),
            )
    except AppSetPatchError:
        logger.exception("ApplicationSet patch failed")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=(
                "Cluster YAMLs committed but failed to update ApplicationSet "
                f"projects list at {APPLICATIONSET_PATH}."
            ),
        )
    except Exception:
        logger.exception("Failed to update ApplicationSet")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Cluster YAMLs committed but failed to update ApplicationSet.",
        )

    # Also patch the adot-collector ApplicationSet so the new environment is
    # included in its observability match-expressions. Same pattern: read base,
    # patch, commit on the feature branch. Idempotent.
    adot_patched = False
    try:
        adot_content = gh.get_file_content(ADOT_COLLECTOR_PATH)
        updated_adot, adot_changed = patch_environment_match_values(
            adot_content, request.project_name()
        )
        if adot_changed:
            gh.update_file(
                branch_name,
                ADOT_COLLECTOR_PATH,
                updated_adot,
                f"feat: enable adot-collector for {request.project_name()}",
            )
            adot_patched = True
            logger.info(
                "Patched adot-collector environment list with '%s'",
                request.project_name(),
            )
        else:
            logger.info(
                "adot-collector already lists environment '%s' \u2014 skipping",
                request.project_name(),
            )
    except EnvMatchPatchError:
        logger.exception("adot-collector patch failed")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=(
                "Cluster YAMLs committed but failed to update adot-collector "
                f"environment list at {ADOT_COLLECTOR_PATH}."
            ),
        )
    except Exception:
        logger.exception("Failed to update adot-collector ApplicationSet")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Cluster YAMLs committed but failed to update adot-collector.",
        )

    # PR creation is intentionally disabled — branch + files only.
    # To re-enable, uncomment the block below.
    # try:
    #     pr = gh._repo.create_pull(
    #         title=f"Register cluster: {request.cluster_name()}",
    #         body=_build_cluster_pr_body(request, register_path, values_path),
    #         head=branch_name,
    #         base=settings.argocd_github_base_branch,
    #     )
    # except Exception:
    #     logger.exception("Failed to create cluster PR")
    #     raise HTTPException(
    #         status_code=status.HTTP_502_BAD_GATEWAY,
    #         detail="Files committed but failed to create PR.",
    #     )
    # pr_url = pr.html_url
    # pr_number = pr.number
    # logger.info("Created cluster PR #%d at %s", pr_number, pr_url)

    pr_url = f"https://github.com/{settings.argocd_github_repo_full}/tree/{branch_name}"
    pr_number = None

    # Also create the cluster's "default branch" (= short_env_name) off the base
    # branch. This is referenced by the rendered YAML as `defaultBranch:` and
    # must exist for ArgoCD to track per-cluster overrides. Idempotent: skip if
    # already present; never fails the request if creation has an issue.
    default_branch_ref = request.default_branch()
    default_branch_created = False
    default_branch_url = (
        f"https://github.com/{settings.argocd_github_repo_full}/tree/{default_branch_ref}"
    )
    try:
        if gh.branch_exists(default_branch_ref):
            logger.info(
                "Default branch '%s' already exists — skipping creation",
                default_branch_ref,
            )
        else:
            gh.create_branch(default_branch_ref)
            default_branch_created = True
            logger.info("Created default branch '%s'", default_branch_ref)
    except Exception:
        logger.exception(
            "Failed to create default branch '%s' (non-fatal)", default_branch_ref
        )
        default_branch_url = None

    message = (
        f"Branch '{branch_name}' created with cluster registration files "
        f"for '{request.cluster_name()}'. "
    )
    if default_branch_created:
        message += f"Default branch '{default_branch_ref}' created. "
    elif default_branch_url:
        message += f"Default branch '{default_branch_ref}' already existed. "
    message += "Open a PR manually when ready."

    return ClusterRegistrationResponse(
        success=True,
        message=message,
        branch_name=branch_name,
        pr_url=pr_url,
        pr_number=pr_number,
        files_created=[register_path, values_path]
        + ([APPLICATIONSET_PATH] if appset_patched else [])
        + ([ADOT_COLLECTOR_PATH] if adot_patched else []),
        default_branch_name=default_branch_ref,
        default_branch_url=default_branch_url,
        default_branch_created=default_branch_created,
    )


def _build_cluster_pr_body(
    req: ClusterRegistrationRequest, register_path: str, values_path: str
) -> str:
    return f"""## ArgoCD Cluster Registration

**Cluster:** `{req.cluster_name()}`
**Environment:** `{req.full_env_name}`
**AWS Account:** `{req.aws_account_id}`
**Region:** `{req.aws_region}`
**VPC:** `{req.vpc_id}`

---

### Files Created

- `{register_path}` — cluster metadata
- `{values_path}` — service overrides (appconfig, istio-gw, istio-certs)

---

### Configuration

| Setting | Value |
|---------|-------|
| Server URL | `{req.server_url}` |
| Default Branch | `{req.default_branch()}` |
| Chart Branch | `{req.chart_branch}` |
| autoSync | `{req.auto_sync}` |
| prune | `{req.prune}` |
| selfHeal | `{req.self_heal}` |

---

### Checklist

- [ ] Verify EKS endpoint and CA data are accessible
- [ ] IRSA role `cubic-service-role/{req.cluster_name()}-argocd-registered-role` exists
- [ ] AWS SSM Parameter `/{req.cluster_name()}/eks/caData` is populated
- [ ] Approved by Platform team

---

> _Auto-generated by Infra Portal — Cluster Registration._
"""

