import type { EnvironmentConfig } from '../types/environment';
import {
  DEFAULT_SUBNET_CIDRS,
  DEFAULT_VPC_ENDPOINTS,
} from '../types/environment';

export function getDefaultConfig(): EnvironmentConfig {
  const defaultVpc = {
    createVpc: true,
    createInternetGateway: true,
    createNatGateway: true,
    createVpcEndpoints: true,
    createEgressNetworkFirewall: false,
    createEksControlPlaneSubnets: true,
    availabilityZones: [] as string[],
    environmentTier: 'nonprod',
    vpcType: 'workload',
    ipamPoolName: 'internal-pool-non-routable',
    ipv4NetmaskLength: 19,
    workloadSubnetCidrs: { ...DEFAULT_SUBNET_CIDRS },
    natGatewayDeployment: 'one_per_az',
    vpcEndpoints: [...DEFAULT_VPC_ENDPOINTS],
    enableFlowLogs: true,
    flowLogsRetentionDays: 30,
    attachToTransitGateway: true,
    transitGatewayRouteTableToAttach: 'regional',
    transitGatewayRouteTablesToPropagate: ['regional', 'internal'],
    tgwSubnetNames: ['eks_control_plane_workloads', 'app'],
    tgwDestinationCidrs: ['10.0.0.0/8'],
    customRoutes: [],
    associateWithPrivateHostedZones: true,
    privateHostedZonesProdToAssociate: [],
    privateHostedZonesNonProdToAssociate: [],
    connectToPhz: false,
    appSubnetCustomTags: {},
  };

  return {
    environment: '',
    business: 'int-workloads',
    platformName: 'development',
    createCrossClusterIam: true,
    deployApiGateway: true,
    projectName: 'Cubic',
    name: 'internal',
    tags: {
      Environment: '',
      Team: 'int-workloads',
      Application: 'EKS',
      Terraform: 'true',
    },
    appConfigManagement: {
      create: true,
      sopsKmsKey: {
        deletionWindowInDays: 30,
        createReplica: false,
      },
      githubActionsOrgRepoNameList: ['repo:Caylent-Cubic/*'],
    },
    bastionConfiguration: {
      deployBastion: true,
      amiId: '',
      instanceType: 't3.micro',
      name: 'bastion',
      egressCidrBlocks: ['0.0.0.0/0'],
      egressSecurityGroups: [],
      iamRolePath: '/cubic-service-role/',
    },
    elasticacheClusters: {},
    vpcPrimary: {
      ...defaultVpc,
      availabilityZones: ['us-west-2a', 'us-west-2b', 'us-west-2c'],
    },
    vpcSecondary: {
      ...defaultVpc,
      availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c'],
    },
    vpcFlowLogsIam: {
      createRole: true,
      trustedRoleServices: ['vpc-flow-logs.amazonaws.com'],
      createPolicy: true,
    },
    mskClusters: {},
    mskTopicsPerCluster: {},
    rdsClusters: {},
    rdsAuroraDefaults: {},
    rdsAuroraItems: {},
    eksClusters: {},
    ingressWebRules: '',
    allowHttpsDomains: [],
    blockedCountries: [],
    blockAllTrafficRule: '',
    advancedIdsRules: '',
    threatDetectionRules: '',
    s3Buckets: {},
    sftpConnector: {},
    settlementFilepush: {},
    settlementFilepull: {},
    settlementObservability: {},
    createK170v: false,
    k170vAmiId: '',
    k170vInstanceType: 't2.xlarge',
    k170vVolumeSize: 100,
    k170vAdminCidrBlocks: ['10.0.0.0/8'],
    oraGoldenGate: {},
    verifiedAccessEndpoints: {},
  };
}
